package src;

/**
 *
 * @author pnrv2
 */
import javax.swing.table.DefaultTableModel;

import java.sql.SQLException;
import javax.swing.JOptionPane;

import res.interfazDB.ManejoUIClientes;
import lista.ListaCola;
import res.Clientes;

public class GestionarClientes extends javax.swing.JPanel {

    private ManejoUIClientes manager;
    private Clientes provElim;
    /**
     * Creates new form GestionarProveedores
     */
    public GestionarClientes() {
        manager = new ManejoUIClientes();
        provElim = null;
        initComponents();
        
        try{
            ListaCola<Clientes> cola = manager.consulta(1, null);
            llenarTabla(cola);
        }catch(SQLException sqlE){}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        btnGroupEliminar = new javax.swing.ButtonGroup();
        opcionesPane = new javax.swing.JPanel();
        windowOptions = new javax.swing.JPanel();
        ventanaAgregar = new javax.swing.JPanel();
        labelAccion = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfNC = new javax.swing.JTextField();
        errorLabelAgregar = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        tfSaldo = new javax.swing.JTextField();
        ventanaConsultar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        errorLabelConsultar = new javax.swing.JLabel();
        tipoConsultaLabel = new javax.swing.JLabel();
        tfIDProv = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jrbTodos = new javax.swing.JRadioButton();
        jrbID = new javax.swing.JRadioButton();
        jrbNombre = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        ventanaModificar = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        errorLabelModificar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfIdProvModificar = new javax.swing.JTextField();
        btnBuscarModificar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tfNombreProvModificar = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        tfTelProvModificar = new javax.swing.JTextField();
        ventanaEliminar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        errorLabelEliminar = new javax.swing.JLabel();
        lbEliminar = new javax.swing.JLabel();
        tfEliminar = new javax.swing.JTextField();
        btnBuscarEliminar = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        rbIDEliminar = new javax.swing.JRadioButton();
        rbNombreEliminar = new javax.swing.JRadioButton();
        cabeceraOpcionesPane = new javax.swing.JPanel();
        tituloOpcionesLabel = new javax.swing.JLabel();
        botonesPane = new javax.swing.JPanel();
        btnAgregarWindow = new javax.swing.JButton();
        btnConsultarWindow = new javax.swing.JButton();
        btnModificarWindow = new javax.swing.JButton();
        btnEliminarWindow = new javax.swing.JButton();
        tituloPrincipalPane = new javax.swing.JPanel();
        tituloPrincipalLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProveedores = new javax.swing.JTable();

        opcionesPane.setLayout(new java.awt.BorderLayout());

        windowOptions.setLayout(new java.awt.CardLayout());

        labelAccion.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelAccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAccion.setText("Agregar Clientes");

        jLabel4.setText("Nombre: *");

        tfNC.setText("Ingrese el Nombre del Cliente");
        tfNC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfNCMouseClicked(evt);
            }
        });
        tfNC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNCActionPerformed(evt);
            }
        });

        errorLabelAgregar.setForeground(new java.awt.Color(255, 0, 0));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jLabel10.setText("Saldo");

        tfSaldo.setText("Ingrese el Saldo del Cliente");
        tfSaldo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfSaldoMouseClicked(evt);
            }
        });
        tfSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSaldoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ventanaAgregarLayout = new javax.swing.GroupLayout(ventanaAgregar);
        ventanaAgregar.setLayout(ventanaAgregarLayout);
        ventanaAgregarLayout.setHorizontalGroup(
            ventanaAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaAgregarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ventanaAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventanaAgregarLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(ventanaAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(errorLabelAgregar)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ventanaAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNC, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                            .addComponent(tfSaldo))
                        .addGap(38, 38, 38))
                    .addComponent(labelAccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventanaAgregarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregar)
                .addGap(149, 149, 149))
        );
        ventanaAgregarLayout.setVerticalGroup(
            ventanaAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaAgregarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(labelAccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(errorLabelAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ventanaAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfNC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ventanaAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAgregar)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        windowOptions.add(ventanaAgregar, "Agregar");
        ventanaAgregar.getAccessibleContext().setAccessibleName("");
        ventanaAgregar.getAccessibleContext().setAccessibleDescription("");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Consultar Cliente");

        errorLabelConsultar.setForeground(new java.awt.Color(255, 0, 0));

        tipoConsultaLabel.setText("ID Proveedor:");

        tfIDProv.setText("Ingrese el ID del Cliente");
        tfIDProv.setEnabled(false);
        tfIDProv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfIDProvMouseClicked(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnGroup.add(jrbTodos);
        jrbTodos.setSelected(true);
        jrbTodos.setText("Todos");
        jrbTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbTodosActionPerformed(evt);
            }
        });

        btnGroup.add(jrbID);
        jrbID.setText("ID");
        jrbID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbIDActionPerformed(evt);
            }
        });

        btnGroup.add(jrbNombre);
        jrbNombre.setText("Nombre");
        jrbNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbNombreActionPerformed(evt);
            }
        });

        jLabel8.setText("Tipo de Consulta:");

        javax.swing.GroupLayout ventanaConsultarLayout = new javax.swing.GroupLayout(ventanaConsultar);
        ventanaConsultar.setLayout(ventanaConsultarLayout);
        ventanaConsultarLayout.setHorizontalGroup(
            ventanaConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaConsultarLayout.createSequentialGroup()
                .addGroup(ventanaConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventanaConsultarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE))
                    .addGroup(ventanaConsultarLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(ventanaConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(errorLabelConsultar)
                            .addGroup(ventanaConsultarLayout.createSequentialGroup()
                                .addComponent(tipoConsultaLabel)
                                .addGroup(ventanaConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ventanaConsultarLayout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(btnBuscar))
                                    .addGroup(ventanaConsultarLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfIDProv, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(32, 32, 32)))
                .addContainerGap())
            .addGroup(ventanaConsultarLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jrbTodos)
                .addGap(18, 18, 18)
                .addComponent(jrbID)
                .addGap(18, 18, 18)
                .addComponent(jrbNombre)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ventanaConsultarLayout.setVerticalGroup(
            ventanaConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaConsultarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ventanaConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbTodos)
                    .addComponent(jrbID)
                    .addComponent(jrbNombre))
                .addGap(18, 18, 18)
                .addComponent(errorLabelConsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ventanaConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoConsultaLabel)
                    .addComponent(tfIDProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addContainerGap(192, Short.MAX_VALUE))
        );

        windowOptions.add(ventanaConsultar, "Consultar");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Modificar Clientes");
        jLabel6.setToolTipText("");

        errorLabelModificar.setForeground(new java.awt.Color(255, 0, 0));

        jLabel2.setText("ID Cliente:");

        tfIdProvModificar.setText("Ingrese el ID del Cliente");
        tfIdProvModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfIdProvModificarMouseClicked(evt);
            }
        });

        btnBuscarModificar.setText("Buscar");
        btnBuscarModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarModificarActionPerformed(evt);
            }
        });

        jLabel7.setText("Nombre Cliente:");

        tfNombreProvModificar.setText("Ingrese el nombre del Cliente");
        tfNombreProvModificar.setEnabled(false);
        tfNombreProvModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfNombreProvModificarMouseClicked(evt);
            }
        });
        tfNombreProvModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombreProvModificarActionPerformed(evt);
            }
        });

        btnModificar.setText("Guardar Cambios");
        btnModificar.setEnabled(false);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        jLabel11.setText("Saldo Cliente");

        tfTelProvModificar.setText("Ingrese el Telefono del Proveedor");
        tfTelProvModificar.setEnabled(false);
        tfTelProvModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfTelProvModificarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ventanaModificarLayout = new javax.swing.GroupLayout(ventanaModificar);
        ventanaModificar.setLayout(ventanaModificarLayout);
        ventanaModificarLayout.setHorizontalGroup(
            ventanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaModificarLayout.createSequentialGroup()
                .addGroup(ventanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventanaModificarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ventanaModificarLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(errorLabelModificar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(ventanaModificarLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(ventanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ventanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfTelProvModificar)
                            .addComponent(tfNombreProvModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                            .addComponent(tfIdProvModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(ventanaModificarLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(btnBuscarModificar)
                .addGap(30, 30, 30)
                .addComponent(btnModificar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ventanaModificarLayout.setVerticalGroup(
            ventanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaModificarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(errorLabelModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ventanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfIdProvModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ventanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfNombreProvModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ventanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfTelProvModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(ventanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarModificar)
                    .addComponent(btnModificar))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        windowOptions.add(ventanaModificar, "Modificar");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Eliminar Cliente");

        errorLabelEliminar.setForeground(new java.awt.Color(255, 0, 0));

        lbEliminar.setText("ID lCliente:");

        tfEliminar.setText("Ingrese el Id del Cliente");
        tfEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfEliminarMouseClicked(evt);
            }
        });

        btnBuscarEliminar.setText("Buscar");
        btnBuscarEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEliminarActionPerformed(evt);
            }
        });

        btnConfirm.setText("Eliminar");
        btnConfirm.setEnabled(false);
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        jLabel9.setText("Tipo de Consulta:");

        btnGroupEliminar.add(rbIDEliminar);
        rbIDEliminar.setSelected(true);
        rbIDEliminar.setText("ID");
        rbIDEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbIDEliminarActionPerformed(evt);
            }
        });

        btnGroupEliminar.add(rbNombreEliminar);
        rbNombreEliminar.setText("Nombre");
        rbNombreEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNombreEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ventanaEliminarLayout = new javax.swing.GroupLayout(ventanaEliminar);
        ventanaEliminar.setLayout(ventanaEliminarLayout);
        ventanaEliminarLayout.setHorizontalGroup(
            ventanaEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventanaEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(ventanaEliminarLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(ventanaEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventanaEliminarLayout.createSequentialGroup()
                        .addComponent(rbIDEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbNombreEliminar))
                    .addComponent(jLabel9)
                    .addComponent(errorLabelEliminar)
                    .addGroup(ventanaEliminarLayout.createSequentialGroup()
                        .addGroup(ventanaEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbEliminar)
                            .addComponent(btnBuscarEliminar))
                        .addGap(18, 18, 18)
                        .addGroup(ventanaEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventanaEliminarLayout.createSequentialGroup()
                                .addComponent(btnConfirm)
                                .addGap(36, 36, 36)))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        ventanaEliminarLayout.setVerticalGroup(
            ventanaEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaEliminarLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ventanaEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbIDEliminar)
                    .addComponent(rbNombreEliminar))
                .addGap(10, 10, 10)
                .addComponent(errorLabelEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ventanaEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEliminar)
                    .addComponent(tfEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ventanaEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarEliminar)
                    .addComponent(btnConfirm))
                .addContainerGap(156, Short.MAX_VALUE))
        );

        windowOptions.add(ventanaEliminar, "Eliminar");

        opcionesPane.add(windowOptions, java.awt.BorderLayout.CENTER);

        cabeceraOpcionesPane.setLayout(new java.awt.BorderLayout());

        tituloOpcionesLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tituloOpcionesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloOpcionesLabel.setText("OPCIONES");
        tituloOpcionesLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cabeceraOpcionesPane.add(tituloOpcionesLabel, java.awt.BorderLayout.NORTH);

        btnAgregarWindow.setText("Agregar");
        btnAgregarWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarWindowActionPerformed(evt);
            }
        });
        botonesPane.add(btnAgregarWindow);

        btnConsultarWindow.setText("Consultar");
        btnConsultarWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarWindowActionPerformed(evt);
            }
        });
        botonesPane.add(btnConsultarWindow);

        btnModificarWindow.setText("Modificar");
        btnModificarWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarWindowActionPerformed(evt);
            }
        });
        botonesPane.add(btnModificarWindow);

        btnEliminarWindow.setText("Eliminar");
        btnEliminarWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarWindowActionPerformed(evt);
            }
        });
        botonesPane.add(btnEliminarWindow);

        cabeceraOpcionesPane.add(botonesPane, java.awt.BorderLayout.CENTER);

        opcionesPane.add(cabeceraOpcionesPane, java.awt.BorderLayout.NORTH);

        tituloPrincipalLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        tituloPrincipalLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloPrincipalLabel.setText("Gestion Clientes");
        tituloPrincipalLabel.setToolTipText("");
        tituloPrincipalLabel.setAutoscrolls(true);
        tituloPrincipalLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout tituloPrincipalPaneLayout = new javax.swing.GroupLayout(tituloPrincipalPane);
        tituloPrincipalPane.setLayout(tituloPrincipalPaneLayout);
        tituloPrincipalPaneLayout.setHorizontalGroup(
            tituloPrincipalPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tituloPrincipalPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloPrincipalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE)
                .addContainerGap())
        );
        tituloPrincipalPaneLayout.setVerticalGroup(
            tituloPrincipalPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tituloPrincipalPaneLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(tituloPrincipalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        tablaProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Saldo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaProveedores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloPrincipalPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(opcionesPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tituloPrincipalPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(opcionesPane, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfNCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfNCMouseClicked
        if(tfNC.isEnabled())
            tfNC.setText("");
    }//GEN-LAST:event_tfNCMouseClicked

    private void jrbTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbTodosActionPerformed
        tfIDProv.setEnabled(false);
    }//GEN-LAST:event_jrbTodosActionPerformed

    private void jrbIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbIDActionPerformed
        tfIDProv.setEnabled(true);
        tipoConsultaLabel.setText("ID Cliente:");
        tfIDProv.setText("Ingrese el ID del Cliente:");
    }//GEN-LAST:event_jrbIDActionPerformed

    private void jrbNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbNombreActionPerformed
        tfIDProv.setEnabled(true);
        tipoConsultaLabel.setText("Nombre Cliente:");
        tfIDProv.setText("Ingrese el nombre del Cliente");
    }//GEN-LAST:event_jrbNombreActionPerformed

    private void tfIDProvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfIDProvMouseClicked
        if(tfIDProv.isEnabled())
            tfIDProv.setText("");
    }//GEN-LAST:event_tfIDProvMouseClicked

    private void tfIdProvModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfIdProvModificarMouseClicked
        if(tfIdProvModificar.isEnabled())
            tfIdProvModificar.setText("");
    }//GEN-LAST:event_tfIdProvModificarMouseClicked

    private void btnBuscarModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarModificarActionPerformed
        int in = 0;
        Object obj = null;
        ListaCola<Clientes> cola;
        Clientes proveedor;
        
        try{
            in = Integer.parseInt(tfIdProvModificar.getText());
            obj = in;
        }catch(NumberFormatException nfE){
            errorLabelModificar.setText("ID no valido");
        }
        try{
            if(obj != null){
                cola = manager.consulta(3, obj);
                
                if(cola.hasNext()){
                    proveedor = cola.pop();
                    tfNombreProvModificar.setText(proveedor.getNombre());
                    tfTelProvModificar.setText(proveedor.getSaldo());
                    
                    if(errorLabelModificar.getText().length() != 0)
                        errorLabelModificar.setText("");
                    
                    tfIdProvModificar.setEnabled(false);
                    tfNombreProvModificar.setEnabled(true);
                    tfTelProvModificar.setEnabled(true);
                    btnBuscarModificar.setEnabled(false);
                    btnModificar.setEnabled(true);
                }else{
                    JOptionPane.showMessageDialog(this, "No existe tal cliente", "Id inexistente", JOptionPane.WARNING_MESSAGE);
                }
                
                
                
            }
        }catch(SQLException sqlE){
            JOptionPane.showMessageDialog(this, "Error al realizar busqueda: \n" + sqlE.getMessage(), "Error de Busqueda.", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnBuscarModificarActionPerformed

    private void tfNombreProvModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfNombreProvModificarMouseClicked
        if(tfNC.isEnabled())
            tfNC.setText("");
    }//GEN-LAST:event_tfNombreProvModificarMouseClicked

    private void tfEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfEliminarMouseClicked
        if(tfEliminar.isEnabled())
            tfEliminar.setText("");
    }//GEN-LAST:event_tfEliminarMouseClicked

    private void btnBuscarEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEliminarActionPerformed
        int selectedOpc = 0;
        Object obj = null;
        ListaCola<Clientes> res;
        if(rbIDEliminar.isSelected()){
            int in;
            selectedOpc = 3;
            try{
                in = Integer.parseInt(tfEliminar.getText());
                obj = in;
            }catch(NumberFormatException nfE){
                errorLabelEliminar.setText("Valor no numerico");
            }
        }else if(rbNombreEliminar.isSelected()){
            String nombre = "";
            selectedOpc = 2;
            nombre = tfEliminar.getText();
            if(nombre.length() != 0){
                obj = nombre;
            }else{
                errorLabelEliminar.setText("Valor no ingresado");
            }
        }
        
        if(obj != null){
            try{
                res = manager.consulta(selectedOpc, obj);
                if(!res.hasNext())
                    JOptionPane.showMessageDialog(this, "No existe tal cliente", "Cliente no existente.", JOptionPane.WARNING_MESSAGE);
                else{
                    if(errorLabelEliminar.getText().length() != 0)
                        errorLabelEliminar.setText("");
                    
                    tfEliminar.setEnabled(false);
                    btnBuscarEliminar.setEnabled(false);
                    btnConfirm.setEnabled(true);
                    provElim = res.pop();
                    JOptionPane.showMessageDialog(this, "Cliente:\n" + provElim, "Cliente encontrado", JOptionPane.INFORMATION_MESSAGE);
                }
            }catch(SQLException sqlE){
                JOptionPane.showMessageDialog(this, "Error en la eliminacion: \n" + sqlE.getMessage(), "Error eliminacion", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnBuscarEliminarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String nombre = tfNC.getText();
        String sTelefono = tfSaldo.getText();
        int telefono = 0;
        if(nombre.length() != 0){
            try {
                telefono = (sTelefono.length() != 0) ? Integer.parseInt(sTelefono) : 0;
            } catch(NumberFormatException nfE) {
                errorLabelAgregar.setText("Saldo no valido");
                return;
            }
            try {
                manager.agregar(nombre, telefono);
                if(errorLabelAgregar.getText().length() != 0)
                    errorLabelAgregar.setText("");
                JOptionPane.showMessageDialog(this, "Cliente Agregado", "Insercion Exitosa", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error al agregar usuario: \n" + ex.getMessage(), "Error con la base de datos.", JOptionPane.ERROR_MESSAGE);
            }
            
            try{
                ListaCola<Clientes> cola = manager.consulta(1, null);
                if(cola.hasNext())
                    llenarTabla(cola);
            }catch(SQLException sqlE){}
            
        }else{
            errorLabelAgregar.setText("No se ingreso ningun valor");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        int selectedOpc = 0;
        Object obj = null;
        ListaCola<Clientes> cola;
        if(jrbTodos.isSelected()){
            selectedOpc = 1;
        }else if(jrbID.isSelected()){
            selectedOpc = 3;
            int in = 0;
            try{
                if(tfIDProv.getText().length() != 0){
                    in = Integer.parseInt(tfIDProv.getText());
                    obj = in;
                }else
                    errorLabelConsultar.setText("No se ingreso ningun valor");
            }catch(NumberFormatException nfE){
                errorLabelConsultar.setText("No es un numero entero");
            }
        }else if(jrbNombre.isSelected()){
            selectedOpc = 2;
            String nombre = tfIDProv.getText();
            if(nombre.length() != 0 && !nombre.equals("Ingrese el nombre del Cliente")){
                
                    obj = nombre;
                    
            }else{
                errorLabelConsultar.setText("No se ingreso ningun valor");
            }
        }
        
        try{
            if((obj == null && selectedOpc == 1) || (obj != null && selectedOpc != 1)){
                cola = manager.consulta(selectedOpc, obj);
                if(errorLabelConsultar.getText().length() != 0)
                    errorLabelConsultar.setText("");
                if(!cola.hasNext()){
                    JOptionPane.showMessageDialog(this,"No existen elementos", "Elementos inexistentes", JOptionPane.WARNING_MESSAGE);
                    llenarTabla(cola);
                }else{
                    llenarTabla(cola);
                    if(jrbID.isSelected())
                        tfIDProv.setText("Ingrese el ID del Cliente");
                    else if(jrbNombre.isSelected())
                        tfIDProv.setText("Ingrese el nombre del Cliente");
                }
            }
            
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(this, "Error al agregar usuario: \n" +ex.getMessage(), "Error al Agregar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int id, telefono = 0;
        String nombre = "",sTelefono = "";
        boolean res;
        try{
            id = Integer.parseInt(tfIdProvModificar.getText());
            
            nombre = tfNombreProvModificar.getText();
            sTelefono = tfTelProvModificar.getText();
            if(nombre.length() != 0){
                try {
                    telefono = (sTelefono.length() != 0) ? Integer.parseInt(sTelefono) : 0;
                } catch(NumberFormatException nfE) {
                    errorLabelModificar.setText("Saldo no valido");
                    return;
                }
                
                res = manager.modificar(id, nombre, telefono);
                
                
                if(!res)
                    JOptionPane.showMessageDialog(this, "No se pudo realizar la consulta", "Problema al consultar", JOptionPane.WARNING_MESSAGE);
                
                if(errorLabelModificar.getText().length() != 0)
                    errorLabelModificar.setText("");
                
                JOptionPane.showMessageDialog(this, "Modificacion exitosa.", "Modificacion realizada", JOptionPane.INFORMATION_MESSAGE);
                tfIdProvModificar.setEnabled(true);
                tfNombreProvModificar.setEnabled(false);
                tfTelProvModificar.setEnabled(false);
                btnBuscarModificar.setEnabled(true);
                btnModificar.setEnabled(false);
            
                tfIdProvModificar.setText("Ingrese el ID del Cliente");
                tfNombreProvModificar.setText("Ingrese el nombre del Cliente");
                tfTelProvModificar.setText("Ingrese el telefono del Cliente");
            }else{
                errorLabelModificar.setText("No ingreso nuevo nombre.");
            }
            
        }catch(NumberFormatException nfE){
            errorLabelModificar.setText("ID no valido");
        }catch(SQLException sqlE){
            JOptionPane.showMessageDialog(this, "Error en la busqueda: \n" + sqlE.getMessage(), "Error de Busqueda.", JOptionPane.ERROR_MESSAGE);
        }

        try{
            ListaCola<Clientes> cola = manager.consulta(1, null);
            llenarTabla(cola);
        }catch(SQLException sqlE){}
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void rbIDEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbIDEliminarActionPerformed
        if(rbIDEliminar.isSelected()){
            lbEliminar.setText("ID Clienter:");
            tfEliminar.setText("Ingrese el Id del Cliente");
            tfEliminar.setEnabled(true);
            btnBuscarEliminar.setEnabled(true);
            btnConfirm.setEnabled(false);
        }
    }//GEN-LAST:event_rbIDEliminarActionPerformed

    private void rbNombreEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNombreEliminarActionPerformed
        if(rbNombreEliminar.isSelected()){
            lbEliminar.setText("Nombre Cliente:");
            tfEliminar.setText("Ingrese el nombre del Cliente");
            tfEliminar.setEnabled(true);
            btnBuscarEliminar.setEnabled(true);
            btnConfirm.setEnabled(false);
        }
    }//GEN-LAST:event_rbNombreEliminarActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        int in;
        Object obj = null;
        boolean res;
        
        if(rbIDEliminar.isSelected()){
            try{
                if(tfEliminar.getText().length() != 0){
                    in = Integer.parseInt(tfEliminar.getText());
                    obj = in;
                }
            }catch(NumberFormatException nfE){
                errorLabelEliminar.setText("Valor no numerico");
            }
        }else if(rbNombreEliminar.isSelected()){
            String nombre = tfEliminar.getText();
            if(nombre.length() != 0)
                obj = nombre;
            else
                errorLabelEliminar.setText("No se ingresaron valores");
        }
        
        if(obj != null){
            try{
                in = JOptionPane.showConfirmDialog(this, "Desea eliminar al Cliente cuyos datos son:\nNombre: " + provElim.getNombre() + "\nID: " + provElim.getId(), "Confirmacion", JOptionPane.YES_NO_OPTION);
                if(in == JOptionPane.YES_OPTION){
                    res = manager.eliminar(obj);
                    if(!res)
                        JOptionPane.showMessageDialog(this, "Eliminacion no realizada", "Problema de Eliminacion.", JOptionPane.WARNING_MESSAGE);
                    else{
                        if(errorLabelEliminar.getText().length() != 0)
                            errorLabelEliminar.setText("");

                        tfEliminar.setEnabled(true);
                        btnBuscarEliminar.setEnabled(true);
                        btnConfirm.setEnabled(false);
                    }
                }else{
                        if(errorLabelEliminar.getText().length() != 0)
                            errorLabelEliminar.setText("");
                    
                        btnBuscarEliminar.setEnabled(true);
                        btnConfirm.setEnabled(false);
                }
            }catch(SQLException sqlE){
                JOptionPane.showMessageDialog(this, "Eliminacion no realizada: \n" + sqlE.getMessage(), "Error en la Eliminacion.", JOptionPane.ERROR_MESSAGE);
            }
            
            try{
                ListaCola<Clientes> cola = manager.consulta(1, null);
                llenarTabla(cola);
            }catch(SQLException sqlE){}
            
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void tfSaldoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfSaldoMouseClicked
        if(tfSaldo.isEnabled())
            tfSaldo.setText("");
    }//GEN-LAST:event_tfSaldoMouseClicked

    private void tfTelProvModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfTelProvModificarMouseClicked
        if(tfTelProvModificar.isEnabled())
            tfTelProvModificar.setText("");
    }//GEN-LAST:event_tfTelProvModificarMouseClicked

    private void tfNCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNCActionPerformed

    private void tfSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSaldoActionPerformed

    private void btnEliminarWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarWindowActionPerformed
        java.awt.CardLayout card = (java.awt.CardLayout)windowOptions.getLayout();

        errorLabelEliminar.setText("");
        lbEliminar.setText("ID Cliente:");
        tfEliminar.setText("Ingrese el Id del Cliente");
        rbIDEliminar.setSelected(true);

        btnBuscarEliminar.setEnabled(true);
        btnConfirm.setEnabled(false);

        card.show(windowOptions, "Eliminar");
    }//GEN-LAST:event_btnEliminarWindowActionPerformed

    private void btnModificarWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarWindowActionPerformed
        java.awt.CardLayout card = (java.awt.CardLayout)windowOptions.getLayout();

        errorLabelModificar.setText("");

        tfIdProvModificar.setText("Ingrese el ID del Cliente");
        tfIdProvModificar.setEnabled(true);
        tfNombreProvModificar.setText("Ingrese el nombre del Cliente");
        tfNombreProvModificar.setEnabled(false);
        tfTelProvModificar.setText("Ingrese el saldo del Cliente");
        tfTelProvModificar.setEnabled(false);

        btnBuscarModificar.setEnabled(true);
        btnModificar.setEnabled(false);

        card.show(windowOptions, "Modificar");
    }//GEN-LAST:event_btnModificarWindowActionPerformed

    private void btnConsultarWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarWindowActionPerformed
        java.awt.CardLayout card = (java.awt.CardLayout)windowOptions.getLayout();
        errorLabelConsultar.setText("");

        tipoConsultaLabel.setText("ID Cliente:");
        jrbTodos.setSelected(true);
        tfIDProv.setText("Ingrese el ID del Cliente");
        tfIDProv.setEnabled(false);

        card.show(windowOptions, "Consultar");
    }//GEN-LAST:event_btnConsultarWindowActionPerformed

    private void btnAgregarWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarWindowActionPerformed
        java.awt.CardLayout card = (java.awt.CardLayout)windowOptions.getLayout();
        tfNC.setText("Ingrese el nombre del Cliente");
        tfSaldo.setText("Ingrese el saldo del cliente");
        errorLabelAgregar.setText("");

        card.show(windowOptions, "Agregar");
    }//GEN-LAST:event_btnAgregarWindowActionPerformed

    private void tfNombreProvModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombreProvModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombreProvModificarActionPerformed
    
    private void llenarTabla(ListaCola<Clientes> cola){
        Clientes proveedor;
        DefaultTableModel modelo = (DefaultTableModel) tablaProveedores.getModel();
        
        while(modelo.getRowCount() != 0)
            modelo.removeRow(0);
        
        while(cola.hasNext()){
            proveedor = cola.pop();
            
            modelo.addRow(new Object[]{proveedor.getId(), proveedor.getNombre(), proveedor.getSaldo()});
        }
        tablaProveedores.setModel(modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botonesPane;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregarWindow;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarEliminar;
    private javax.swing.JButton btnBuscarModificar;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnConsultarWindow;
    private javax.swing.JButton btnEliminarWindow;
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.ButtonGroup btnGroupEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnModificarWindow;
    private javax.swing.JPanel cabeceraOpcionesPane;
    private javax.swing.JLabel errorLabelAgregar;
    private javax.swing.JLabel errorLabelConsultar;
    private javax.swing.JLabel errorLabelEliminar;
    private javax.swing.JLabel errorLabelModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jrbID;
    private javax.swing.JRadioButton jrbNombre;
    private javax.swing.JRadioButton jrbTodos;
    private javax.swing.JLabel labelAccion;
    private javax.swing.JLabel lbEliminar;
    private javax.swing.JPanel opcionesPane;
    private javax.swing.JRadioButton rbIDEliminar;
    private javax.swing.JRadioButton rbNombreEliminar;
    private javax.swing.JTable tablaProveedores;
    private javax.swing.JTextField tfEliminar;
    private javax.swing.JTextField tfIDProv;
    private javax.swing.JTextField tfIdProvModificar;
    private javax.swing.JTextField tfNC;
    private javax.swing.JTextField tfNombreProvModificar;
    private javax.swing.JTextField tfSaldo;
    private javax.swing.JTextField tfTelProvModificar;
    private javax.swing.JLabel tipoConsultaLabel;
    private javax.swing.JLabel tituloOpcionesLabel;
    private javax.swing.JLabel tituloPrincipalLabel;
    private javax.swing.JPanel tituloPrincipalPane;
    private javax.swing.JPanel ventanaAgregar;
    private javax.swing.JPanel ventanaConsultar;
    private javax.swing.JPanel ventanaEliminar;
    private javax.swing.JPanel ventanaModificar;
    private javax.swing.JPanel windowOptions;
    // End of variables declaration//GEN-END:variables
}
