/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;

/**
 *
 * @author pnrv2
 */
import javax.swing.table.TableModel;
import javax.swing.table.DefaultTableModel;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import res.interfazDB.ManejoUIProveedores;
import lista.ListaCola;
import res.Persona;

public class GestionarProveedores extends javax.swing.JPanel {

    private ManejoUIProveedores manager;
    
    private boolean queryTodos;
    private boolean queryId;
    private boolean queryNom;
    /**
     * Creates new form GestionarProveedores
     */
    public GestionarProveedores() {
        queryTodos = false;
        queryId = false;
        queryNom = false;
        manager = new ManejoUIProveedores();
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        btnGroupEliminar = new javax.swing.ButtonGroup();
        opcionesPane = new javax.swing.JPanel();
        windowOptions = new javax.swing.JPanel();
        ventanaAgregar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfNombreProv = new javax.swing.JTextField();
        errorLabelAgregar = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        ventanaConsultar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        errorLabelConsultar = new javax.swing.JLabel();
        tipoConsultaLabel = new javax.swing.JLabel();
        tfIDProv = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jrbTodos = new javax.swing.JRadioButton();
        jrbID = new javax.swing.JRadioButton();
        jrbNombre = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        ventanaModificar = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        errorLabelModificar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfIdProvModificar = new javax.swing.JTextField();
        btnBuscarModificar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tfNombreProvModificar = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        ventanaEliminar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        errorLabelEliminar = new javax.swing.JLabel();
        lbEliminar = new javax.swing.JLabel();
        tfEliminar = new javax.swing.JTextField();
        btnBuscarEliminar = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        rbIDEliminar = new javax.swing.JRadioButton();
        rbNombreEliminar = new javax.swing.JRadioButton();
        cabeceraOpcionesPane = new javax.swing.JPanel();
        tituloOpcionesLabel = new javax.swing.JLabel();
        botonesPane = new javax.swing.JPanel();
        btnAgregarWindow = new javax.swing.JButton();
        btnConsultarWindow = new javax.swing.JButton();
        btnModificarWindow = new javax.swing.JButton();
        btnEliminarWindow = new javax.swing.JButton();
        tituloPrincipalPane = new javax.swing.JPanel();
        tituloPrincipalLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProveedores = new javax.swing.JTable();

        opcionesPane.setLayout(new java.awt.BorderLayout());

        windowOptions.setLayout(new java.awt.CardLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Agregar Proveedor");

        jLabel4.setText("Nombre:");

        tfNombreProv.setText("Ingrese Nombre del Proveedor");
        tfNombreProv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfNombreProvMouseClicked(evt);
            }
        });

        errorLabelAgregar.setForeground(new java.awt.Color(255, 0, 0));
        errorLabelAgregar.setText("Error Label");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ventanaAgregarLayout = new javax.swing.GroupLayout(ventanaAgregar);
        ventanaAgregar.setLayout(ventanaAgregarLayout);
        ventanaAgregarLayout.setHorizontalGroup(
            ventanaAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaAgregarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ventanaAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventanaAgregarLayout.createSequentialGroup()
                        .addGap(0, 55, Short.MAX_VALUE)
                        .addGroup(ventanaAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(errorLabelAgregar)
                            .addGroup(ventanaAgregarLayout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(btnAgregar))
                            .addGroup(ventanaAgregarLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfNombreProv, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)))
                        .addGap(0, 38, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        ventanaAgregarLayout.setVerticalGroup(
            ventanaAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaAgregarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(errorLabelAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ventanaAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfNombreProv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAgregar)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        windowOptions.add(ventanaAgregar, "Agregar");
        ventanaAgregar.getAccessibleContext().setAccessibleName("");
        ventanaAgregar.getAccessibleContext().setAccessibleDescription("");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Consultar Proveedor");

        errorLabelConsultar.setForeground(new java.awt.Color(255, 0, 0));
        errorLabelConsultar.setText("Error Label");

        tipoConsultaLabel.setText("ID Proveedor:");

        tfIDProv.setText("Ingrese el ID del Proveedor");
        tfIDProv.setEnabled(false);
        tfIDProv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfIDProvMouseClicked(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnGroup.add(jrbTodos);
        jrbTodos.setText("Todos");
        jrbTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbTodosActionPerformed(evt);
            }
        });

        btnGroup.add(jrbID);
        jrbID.setText("ID");
        jrbID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbIDActionPerformed(evt);
            }
        });

        btnGroup.add(jrbNombre);
        jrbNombre.setText("Nombre");
        jrbNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbNombreActionPerformed(evt);
            }
        });

        jLabel8.setText("Tipo de Consulta:");

        javax.swing.GroupLayout ventanaConsultarLayout = new javax.swing.GroupLayout(ventanaConsultar);
        ventanaConsultar.setLayout(ventanaConsultarLayout);
        ventanaConsultarLayout.setHorizontalGroup(
            ventanaConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaConsultarLayout.createSequentialGroup()
                .addGroup(ventanaConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventanaConsultarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ventanaConsultarLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(ventanaConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(errorLabelConsultar)
                            .addGroup(ventanaConsultarLayout.createSequentialGroup()
                                .addComponent(tipoConsultaLabel)
                                .addGroup(ventanaConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ventanaConsultarLayout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(btnBuscar))
                                    .addGroup(ventanaConsultarLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfIDProv, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(32, 32, 32)))
                .addContainerGap())
            .addGroup(ventanaConsultarLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jrbTodos)
                .addGap(18, 18, 18)
                .addComponent(jrbID)
                .addGap(18, 18, 18)
                .addComponent(jrbNombre)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ventanaConsultarLayout.setVerticalGroup(
            ventanaConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaConsultarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ventanaConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbTodos)
                    .addComponent(jrbID)
                    .addComponent(jrbNombre))
                .addGap(18, 18, 18)
                .addComponent(errorLabelConsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ventanaConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoConsultaLabel)
                    .addComponent(tfIDProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        windowOptions.add(ventanaConsultar, "Consultar");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Modificar Proveedor");
        jLabel6.setToolTipText("");

        errorLabelModificar.setForeground(new java.awt.Color(255, 0, 0));
        errorLabelModificar.setText("Error Label");

        jLabel2.setText("ID Proveedor:");

        tfIdProvModificar.setText("Ingrese el ID del Proveedor");
        tfIdProvModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfIdProvModificarMouseClicked(evt);
            }
        });

        btnBuscarModificar.setText("Buscar");
        btnBuscarModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarModificarActionPerformed(evt);
            }
        });

        jLabel7.setText("Nombre Proveedor:");

        tfNombreProvModificar.setText("Ingrese el nombre del Proveedor");
        tfNombreProvModificar.setEnabled(false);
        tfNombreProvModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfNombreProvModificarMouseClicked(evt);
            }
        });

        btnModificar.setText("Guardar Cambios");
        btnModificar.setEnabled(false);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ventanaModificarLayout = new javax.swing.GroupLayout(ventanaModificar);
        ventanaModificar.setLayout(ventanaModificarLayout);
        ventanaModificarLayout.setHorizontalGroup(
            ventanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaModificarLayout.createSequentialGroup()
                .addGroup(ventanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventanaModificarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ventanaModificarLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(ventanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ventanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNombreProvModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                            .addComponent(tfIdProvModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)))
                    .addGroup(ventanaModificarLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnBuscarModificar)
                        .addGap(30, 30, 30)
                        .addComponent(btnModificar))
                    .addGroup(ventanaModificarLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(errorLabelModificar)))
                .addContainerGap())
        );
        ventanaModificarLayout.setVerticalGroup(
            ventanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaModificarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(errorLabelModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ventanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfIdProvModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ventanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfNombreProvModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ventanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarModificar)
                    .addComponent(btnModificar))
                .addContainerGap(150, Short.MAX_VALUE))
        );

        windowOptions.add(ventanaModificar, "Modificar");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Eliminar Proveedor");

        errorLabelEliminar.setForeground(new java.awt.Color(255, 0, 0));
        errorLabelEliminar.setText("Error Label");

        lbEliminar.setText("ID Proveedor:");

        tfEliminar.setText("Ingrese el Id del Proveedor");
        tfEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfEliminarMouseClicked(evt);
            }
        });

        btnBuscarEliminar.setText("Buscar");
        btnBuscarEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEliminarActionPerformed(evt);
            }
        });

        btnConfirm.setText("Eliminar");
        btnConfirm.setEnabled(false);
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        jLabel9.setText("Tipo de Consulta:");

        btnGroupEliminar.add(rbIDEliminar);
        rbIDEliminar.setText("ID");
        rbIDEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbIDEliminarActionPerformed(evt);
            }
        });

        btnGroupEliminar.add(rbNombreEliminar);
        rbNombreEliminar.setText("Nombre");
        rbNombreEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNombreEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ventanaEliminarLayout = new javax.swing.GroupLayout(ventanaEliminar);
        ventanaEliminar.setLayout(ventanaEliminarLayout);
        ventanaEliminarLayout.setHorizontalGroup(
            ventanaEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventanaEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(ventanaEliminarLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(ventanaEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventanaEliminarLayout.createSequentialGroup()
                        .addComponent(rbIDEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbNombreEliminar))
                    .addComponent(jLabel9)
                    .addComponent(errorLabelEliminar)
                    .addGroup(ventanaEliminarLayout.createSequentialGroup()
                        .addGroup(ventanaEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbEliminar)
                            .addComponent(btnBuscarEliminar))
                        .addGap(18, 18, 18)
                        .addGroup(ventanaEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventanaEliminarLayout.createSequentialGroup()
                                .addComponent(btnConfirm)
                                .addGap(36, 36, 36)))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        ventanaEliminarLayout.setVerticalGroup(
            ventanaEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaEliminarLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ventanaEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbIDEliminar)
                    .addComponent(rbNombreEliminar))
                .addGap(10, 10, 10)
                .addComponent(errorLabelEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ventanaEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEliminar)
                    .addComponent(tfEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ventanaEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarEliminar)
                    .addComponent(btnConfirm))
                .addContainerGap(140, Short.MAX_VALUE))
        );

        windowOptions.add(ventanaEliminar, "Eliminar");

        opcionesPane.add(windowOptions, java.awt.BorderLayout.CENTER);

        cabeceraOpcionesPane.setLayout(new java.awt.BorderLayout());

        tituloOpcionesLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tituloOpcionesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloOpcionesLabel.setText("OPCIONES");
        tituloOpcionesLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cabeceraOpcionesPane.add(tituloOpcionesLabel, java.awt.BorderLayout.NORTH);

        btnAgregarWindow.setText("Agregar");
        btnAgregarWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarWindowActionPerformed(evt);
            }
        });
        botonesPane.add(btnAgregarWindow);

        btnConsultarWindow.setText("Consultar");
        btnConsultarWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarWindowActionPerformed(evt);
            }
        });
        botonesPane.add(btnConsultarWindow);

        btnModificarWindow.setText("Modificar");
        btnModificarWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarWindowActionPerformed(evt);
            }
        });
        botonesPane.add(btnModificarWindow);

        btnEliminarWindow.setText("Eliminar");
        btnEliminarWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarWindowActionPerformed(evt);
            }
        });
        botonesPane.add(btnEliminarWindow);

        cabeceraOpcionesPane.add(botonesPane, java.awt.BorderLayout.CENTER);

        opcionesPane.add(cabeceraOpcionesPane, java.awt.BorderLayout.NORTH);

        tituloPrincipalLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        tituloPrincipalLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloPrincipalLabel.setText("Gestion Proveedores");
        tituloPrincipalLabel.setToolTipText("");
        tituloPrincipalLabel.setAutoscrolls(true);
        tituloPrincipalLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout tituloPrincipalPaneLayout = new javax.swing.GroupLayout(tituloPrincipalPane);
        tituloPrincipalPane.setLayout(tituloPrincipalPaneLayout);
        tituloPrincipalPaneLayout.setHorizontalGroup(
            tituloPrincipalPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tituloPrincipalPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloPrincipalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE)
                .addContainerGap())
        );
        tituloPrincipalPaneLayout.setVerticalGroup(
            tituloPrincipalPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tituloPrincipalPaneLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(tituloPrincipalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        tablaProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaProveedores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloPrincipalPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(opcionesPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tituloPrincipalPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(opcionesPane, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarWindowActionPerformed
        java.awt.CardLayout card = (java.awt.CardLayout)windowOptions.getLayout();
        card.show(windowOptions, "Agregar");
    }//GEN-LAST:event_btnAgregarWindowActionPerformed

    private void btnConsultarWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarWindowActionPerformed
        java.awt.CardLayout card = (java.awt.CardLayout)windowOptions.getLayout();
        card.show(windowOptions, "Consultar");
    }//GEN-LAST:event_btnConsultarWindowActionPerformed

    private void btnModificarWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarWindowActionPerformed
        java.awt.CardLayout card = (java.awt.CardLayout)windowOptions.getLayout();
        card.show(windowOptions, "Modificar");
    }//GEN-LAST:event_btnModificarWindowActionPerformed

    private void btnEliminarWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarWindowActionPerformed
        java.awt.CardLayout card = (java.awt.CardLayout)windowOptions.getLayout();
        card.show(windowOptions, "Eliminar");
    }//GEN-LAST:event_btnEliminarWindowActionPerformed

    private void tfNombreProvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfNombreProvMouseClicked
        tfNombreProv.setText("");
    }//GEN-LAST:event_tfNombreProvMouseClicked

    private void jrbTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbTodosActionPerformed
        queryTodos = true;
        queryId = false;
        queryNom = false;
        tfIDProv.setEnabled(false);
    }//GEN-LAST:event_jrbTodosActionPerformed

    private void jrbIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbIDActionPerformed
        queryId = true;
        queryTodos = false;
        queryNom = false;
        tfIDProv.setEnabled(true);
        tipoConsultaLabel.setText("ID Proveedor:");
    }//GEN-LAST:event_jrbIDActionPerformed

    private void jrbNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbNombreActionPerformed
        queryNom = true;
        queryId = false;
        queryTodos = false;
        tfIDProv.setEnabled(true);
        tipoConsultaLabel.setText("Nombre Proveedor:");
    }//GEN-LAST:event_jrbNombreActionPerformed

    private void tfIDProvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfIDProvMouseClicked
        tfIDProv.setText("");
    }//GEN-LAST:event_tfIDProvMouseClicked

    private void tfIdProvModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfIdProvModificarMouseClicked
        tfIdProvModificar.setText("");
    }//GEN-LAST:event_tfIdProvModificarMouseClicked

    private void btnBuscarModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarModificarActionPerformed
        int in = 0;
        Object obj = null;
        ListaCola<Persona> cola;
        Persona proveedor;
        
        try{
            in = Integer.parseInt(tfIdProvModificar.getText());
            obj = in;
        }catch(NumberFormatException nfE){
            System.out.println("ID no valido en modificar");
        }
        try{
            if(obj != null){
                cola = manager.consulta(obj);
                
                if(cola.hasNext()){
                    proveedor = cola.pop();
                    tfNombreProvModificar.setText(proveedor.getNombre());
                }
                
                tfIdProvModificar.setEnabled(false);
                tfNombreProvModificar.setEnabled(true);
                btnBuscarModificar.setEnabled(false);
                btnModificar.setEnabled(true);
                
            }
        }catch(SQLException sqlE){
            System.out.println("Error al realizar la consulta en modificar");
        }
        
    }//GEN-LAST:event_btnBuscarModificarActionPerformed

    private void tfNombreProvModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfNombreProvModificarMouseClicked
        tfNombreProv.setText("");
    }//GEN-LAST:event_tfNombreProvModificarMouseClicked

    private void tfEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfEliminarMouseClicked
        tfEliminar.setText("");
    }//GEN-LAST:event_tfEliminarMouseClicked

    private void btnBuscarEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEliminarActionPerformed
        int in;
        Object obj = null;
        String nombre = "";
        boolean res;
        if(rbIDEliminar.isSelected()){
            try{
                in = Integer.parseInt(tfEliminar.getText());
                obj = in;
            }catch(NumberFormatException nfE){
                System.out.println("Valor no numerico");
            }
        }else if(rbNombreEliminar.isSelected()){
            nombre = tfEliminar.getText();
            if(nombre.length() != 0){
                obj = nombre;
            }else{
                System.out.println("Valor no ingresado");
            }
        }
        
        if(obj != null){
            try{
                res = manager.eliminar(obj);
                if(!res)
                    System.out.println("Eliminacion no realizada");
                else{
                    btnBuscarEliminar.setEnabled(false);
                    btnConfirm.setEnabled(true);
                }
            }catch(SQLException sqlE){
                System.out.println("Error en la consulta");
            }
        }
    }//GEN-LAST:event_btnBuscarEliminarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        try {
            manager.agregar(tfNombreProv.getText());
        } catch (SQLException ex) {
            System.out.println("Error al agregar usuario: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Object obj = null;
        ListaCola<Persona> cola;
        if(jrbTodos.isSelected()){
            obj = '*';
        }else if(jrbID.isSelected()){
            int in = 0;
            try{
                in = Integer.parseInt(tfIDProv.getText());
                obj = in;
            }catch(NumberFormatException nfE){
                System.out.println("No es un numero entero");
            }
        }else if(jrbNombre.isSelected()){
            String nombre = tfIDProv.getText();
            if(nombre.length() != 0){
                obj = nombre;
            }else{
                System.out.println("No se ingreso ningun valor valido");
            }
        }
        
        try{
            if(obj != null){
                cola = manager.consulta(obj);
                llenarTabla(cola);
            }else{
                System.out.println("No se ingresaron valores");
            }
        }catch(SQLException ex){
            System.out.println("Error al agregar usuario");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int id;
        String nombre = "";
        boolean res;
        try{
            id = Integer.parseInt(tfIdProvModificar.getText());
            
            nombre = tfNombreProvModificar.getText();
            if(nombre.length() != 0){
                res = manager.modificar(id, nombre);
                
                if(!res)
                    System.out.println("No se pudo consultar la consulta");
            }
            
            tfIdProvModificar.setEnabled(true);
            tfNombreProvModificar.setEnabled(false);
            btnBuscarModificar.setEnabled(true);
            btnModificar.setEnabled(false);
            
            tfIdProvModificar.setText("Ingrese el ID del Proveedor");
            tfNombreProvModificar.setText("Ingrese el nombre del Proveedor");
            
        }catch(NumberFormatException nfE){
            
        }catch(SQLException sqlE){
            System.out.println("Error en la consulta de modificacion");
        }
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void rbIDEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbIDEliminarActionPerformed
        lbEliminar.setText("ID Proveedor:");
    }//GEN-LAST:event_rbIDEliminarActionPerformed

    private void rbNombreEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNombreEliminarActionPerformed
        lbEliminar.setText("Nombre Proveedor:");
    }//GEN-LAST:event_rbNombreEliminarActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        int in;
        Object obj = null;
        String nombre = "";
        boolean res;
        
        if(rbIDEliminar.isSelected()){
            try{
                in = Integer.parseInt(tfEliminar.getText());
                obj = in;
            }catch(NumberFormatException nfE){
                System.out.println("Valor no numerico");
            }
        }else if(rbNombreEliminar.isSelected()){
            nombre = tfEliminar.getText();
            if(nombre.length() != 0)
                obj = nombre;
            else
                System.out.println("No se ingresaron valores");
        }
        
        if(obj != null){
            try{
                res = manager.eliminar(obj);
                if(!res)
                    System.out.println("Eliminacion no realizada");
                else{
                    btnBuscarEliminar.setEnabled(true);
                    btnConfirm.setEnabled(false);
                }
            }catch(SQLException sqlE){
                System.out.println("Eliminacion no realizada: " + sqlE.getMessage());
            }
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void llenarTabla(ListaCola<Persona> cola){
        Persona proveedor;
        DefaultTableModel modelo = (DefaultTableModel) tablaProveedores.getModel();
        
        while(modelo.getRowCount() != 0)
            modelo.removeRow(0);
        
        while(cola.hasNext()){
            proveedor = cola.pop();
            
            modelo.addRow(new Object[]{proveedor.getId(), proveedor.getNombre()});
        }
        tablaProveedores.setModel(modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botonesPane;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregarWindow;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarEliminar;
    private javax.swing.JButton btnBuscarModificar;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnConsultarWindow;
    private javax.swing.JButton btnEliminarWindow;
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.ButtonGroup btnGroupEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnModificarWindow;
    private javax.swing.JPanel cabeceraOpcionesPane;
    private javax.swing.JLabel errorLabelAgregar;
    private javax.swing.JLabel errorLabelConsultar;
    private javax.swing.JLabel errorLabelEliminar;
    private javax.swing.JLabel errorLabelModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jrbID;
    private javax.swing.JRadioButton jrbNombre;
    private javax.swing.JRadioButton jrbTodos;
    private javax.swing.JLabel lbEliminar;
    private javax.swing.JPanel opcionesPane;
    private javax.swing.JRadioButton rbIDEliminar;
    private javax.swing.JRadioButton rbNombreEliminar;
    private javax.swing.JTable tablaProveedores;
    private javax.swing.JTextField tfEliminar;
    private javax.swing.JTextField tfIDProv;
    private javax.swing.JTextField tfIdProvModificar;
    private javax.swing.JTextField tfNombreProv;
    private javax.swing.JTextField tfNombreProvModificar;
    private javax.swing.JLabel tipoConsultaLabel;
    private javax.swing.JLabel tituloOpcionesLabel;
    private javax.swing.JLabel tituloPrincipalLabel;
    private javax.swing.JPanel tituloPrincipalPane;
    private javax.swing.JPanel ventanaAgregar;
    private javax.swing.JPanel ventanaConsultar;
    private javax.swing.JPanel ventanaEliminar;
    private javax.swing.JPanel ventanaModificar;
    private javax.swing.JPanel windowOptions;
    // End of variables declaration//GEN-END:variables
}
