/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;

import java.math.RoundingMode;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import lista.ListaCola;
import res.Clientes;
import res.Producto;
import res.VentaProductoUnitario;
import res.interfazDB.ManejoUIClientes;
import res.interfazDB.ManejoUIProductos;
import res.interfazDB.ManejoUIVentas;
import res.interfazDB.ManejoUIVentasDetalladas;
import res.Printer;
/**
 *
 * @author vival
 */
public class GestionarVentas extends javax.swing.JPanel {

    DefaultTableModel modeloTablaAlmacen, modeloPrueba;
    DefaultListModel<String> modeloLista = new DefaultListModel<>();
    private final Printer printer;
    static String[] cabeceraTablaAlmacen = {"ID", "Nombre", "Precio", "Existencia", "Stock", "Unidad de Medida"};
    static float total = 0;
    static String pagoS = "0";
    static ManejoUIProductos mUIP = new ManejoUIProductos();
    static ManejoUIVentas mUIV = new ManejoUIVentas();
    static ManejoUIVentasDetalladas mIUVD = new ManejoUIVentasDetalladas();
    static ManejoUIClientes mUIC = new ManejoUIClientes();
    static String[] pruebaC = {"Producto","Cantidad"};
    /**
     * Creates new form GestionarVentas
     */
    public GestionarVentas() {
        initComponents();
        GrupoBtnRadio.add(btnRadioID);
        GrupoBtnRadio.add(btnRadioCantidad);
        GrupoBtnRadio.add(btnRadioNombre);
        GrupoBtnRadio.add(btnRadioPrecio);
        
        btnRadioID.setSelected(true);
        
        modeloPrueba = new DefaultTableModel(null, pruebaC){
            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 6;
            }
            
        };
        tabla.setModel(modeloPrueba);
        modeloTablaAlmacen = new DefaultTableModel(null,cabeceraTablaAlmacen){
            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 2;
            }
            
        };
        
        ListaCliente.setModel(modeloLista);
        llenarLista("");
        
        tablaAlmacen.setModel(modeloTablaAlmacen);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        tablaAlmacen.setDefaultRenderer(Object.class, centerRenderer);
        tablaAlmacen.getTableHeader().setReorderingAllowed(false);
        tablaAlmacen.getTableHeader().setDefaultRenderer(centerRenderer);
        TableColumnModel columnModel = tablaAlmacen.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(5);
        columnModel.getColumn(1).setPreferredWidth(130);
        columnModel.getColumn(2).setPreferredWidth(20);
        columnModel.getColumn(3).setPreferredWidth(35);
        columnModel.getColumn(4).setPreferredWidth(10);
        columnModel.getColumn(5).setPreferredWidth(80);
        tabla.setDefaultRenderer(Object.class, centerRenderer);
        tabla.getTableHeader().setReorderingAllowed(false);
        tabla.getTableHeader().setDefaultRenderer(centerRenderer);
        TableColumnModel columnModel1 = tabla.getColumnModel();
        columnModel1.getColumn(0).setPreferredWidth(190);
        columnModel1.getColumn(1).setPreferredWidth(1);
        consultarSQL("", 0);

        printer = new Printer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoBtnRadio = new javax.swing.ButtonGroup();
        txtPago = new javax.swing.JTextField();
        BarraBuscar = new javax.swing.JTextField();
        btnAgregarlist2 = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();
        labelTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnNewC = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAlmacen = new javax.swing.JTable();
        ConsVenta = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnRadioID = new javax.swing.JRadioButton();
        btnRadioNombre = new javax.swing.JRadioButton();
        btnRadioPrecio = new javax.swing.JRadioButton();
        btnRadioCantidad = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        txtCambio = new javax.swing.JTextField();
        scroll = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaCliente = new javax.swing.JList<>();
        ClienteTXT = new javax.swing.JTextField();
        ClienteBuscarLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ClienteConPrecio = new javax.swing.JLabel();

        setLayout(null);

        txtPago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPagoKeyTyped(evt);
            }
        });
        add(txtPago);
        txtPago.setBounds(55, 610, 290, 30);

        BarraBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BarraBuscarKeyReleased(evt);
            }
        });
        add(BarraBuscar);
        BarraBuscar.setBounds(440, 40, 480, 30);

        btnAgregarlist2.setText("Agregar");
        btnAgregarlist2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarlist2ActionPerformed(evt);
            }
        });
        add(btnAgregarlist2);
        btnAgregarlist2.setBounds(350, 120, 90, 30);

        btnQuitar.setText("Quitar");
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });
        add(btnQuitar);
        btnQuitar.setBounds(350, 80, 90, 30);

        labelTotal.setText("Total");
        add(labelTotal);
        labelTotal.setBounds(0, 590, 50, 13);

        txtTotal.setEditable(false);
        txtTotal.setText("$");
        add(txtTotal);
        txtTotal.setBounds(54, 580, 290, 30);

        btnNewC.setText("Finalizar compra");
        btnNewC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewCActionPerformed(evt);
            }
        });
        add(btnNewC);
        btnNewC.setBounds(0, 670, 340, 30);

        jLabel1.setText("Pago");
        add(jLabel1);
        jLabel1.setBounds(0, 620, 50, 13);

        tablaAlmacen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaAlmacen);

        add(jScrollPane1);
        jScrollPane1.setBounds(350, 170, 580, 530);

        ConsVenta.setText("Consultar Ventas");
        ConsVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsVentaActionPerformed(evt);
            }
        });
        add(ConsVenta);
        ConsVenta.setBounds(780, 90, 140, 30);

        jLabel3.setText("Filtrar por:");
        add(jLabel3);
        jLabel3.setBounds(450, 80, 80, 13);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Gestionar Ventas");
        add(jLabel4);
        jLabel4.setBounds(560, 0, 200, 40);

        btnRadioID.setText("ID");
        btnRadioID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRadioIDMouseClicked(evt);
            }
        });
        add(btnRadioID);
        btnRadioID.setBounds(450, 100, 50, 21);

        btnRadioNombre.setText("Nombre");
        btnRadioNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRadioNombreMouseClicked(evt);
            }
        });
        add(btnRadioNombre);
        btnRadioNombre.setBounds(450, 140, 90, 21);

        btnRadioPrecio.setText("Precio");
        btnRadioPrecio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRadioPrecioMouseClicked(evt);
            }
        });
        add(btnRadioPrecio);
        btnRadioPrecio.setBounds(540, 100, 80, 21);

        btnRadioCantidad.setText("Existencia");
        btnRadioCantidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRadioCantidadMouseClicked(evt);
            }
        });
        add(btnRadioCantidad);
        btnRadioCantidad.setBounds(540, 140, 120, 21);

        jLabel2.setText("Cambio");
        add(jLabel2);
        jLabel2.setBounds(0, 650, 50, 13);

        txtCambio.setEditable(false);
        txtCambio.setText("$");
        add(txtCambio);
        txtCambio.setBounds(56, 640, 290, 30);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scroll.setViewportView(tabla);

        add(scroll);
        scroll.setBounds(0, 40, 340, 522);

        jLabel5.setText("Buscar");
        add(jLabel5);
        jLabel5.setBounds(370, 40, 50, 20);

        ListaCliente.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ListaCliente.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ListaClienteMouseMoved(evt);
            }
        });
        jScrollPane2.setViewportView(ListaCliente);

        add(jScrollPane2);
        jScrollPane2.setBounds(940, 170, 200, 530);

        ClienteTXT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ClienteTXTKeyReleased(evt);
            }
        });
        add(ClienteTXT);
        ClienteTXT.setBounds(940, 140, 200, 30);

        ClienteBuscarLabel.setText("Buscar");
        add(ClienteBuscarLabel);
        ClienteBuscarLabel.setBounds(940, 110, 60, 30);

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Lista de clientes");
        add(jLabel6);
        jLabel6.setBounds(950, 10, 190, 30);

        ClienteConPrecio.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        add(ClienteConPrecio);
        ClienteConPrecio.setBounds(940, 50, 200, 60);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarlist2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarlist2ActionPerformed
        if (ListaCliente.getSelectedIndex() != -1) {
            if (tablaAlmacen.getSelectedRow() != -1 ) {
                String[] aux = new String[modeloTablaAlmacen.getColumnCount()];
                for (int i = 0; i < aux.length; i++) {
                    aux[i] = modeloTablaAlmacen.getValueAt(tablaAlmacen.getSelectedRow(), i).toString();
                }

               Producto producto = new Producto(Integer.parseInt(aux[0]), aux[1], Integer.parseInt(aux[3]), Integer.parseInt(aux[4]), Float.valueOf(aux[2]), aux[5]);
               //total += producto.getPrecio();
               int i = 0;
               int catidad = 1;
               boolean sobrePasaLaExistencia = false;
               while (i < modeloPrueba.getRowCount()) {
                   if (modeloPrueba.getValueAt(i, 0) instanceof Producto) {
                       if (producto.getId() == ((Producto) (modeloPrueba.getValueAt(i, 0))).getId()) {
                           if (producto.getExistencia() <= (Integer)modeloPrueba.getValueAt(i, 1)) {
                               sobrePasaLaExistencia = true;
                               JOptionPane.showMessageDialog(this, "Ya no queda mas producto en existencia", "Sin existencia", JOptionPane.INFORMATION_MESSAGE);
                           } else {
                               catidad += (Integer)modeloPrueba.getValueAt(i, 1);
                               producto = new Producto(producto.getId(), producto.getNombre(), producto.getExistencia(), producto.getStock(), producto.getPrecio() * catidad, producto.getUM());
                               modeloPrueba.removeRow(i);
                           }

                       }
                       i++;
                   }
                }
                if (!sobrePasaLaExistencia) {
                    total += producto.getPrecio();
                    Object[] pruba321 = {producto,catidad};
                    modeloPrueba.addRow(pruba321);
                }      
            } else {
                JOptionPane.showMessageDialog(this, "Favor de seleccionar un producto de la tabla", "Sin Producto seleccionado", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Favor de seleccionar un Cliente de la lista de clientes", "Sin Cliente seleccionado", JOptionPane.INFORMATION_MESSAGE);
        }
        actualizarTotal();
        actualizarCambio();
    }//GEN-LAST:event_btnAgregarlist2ActionPerformed

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
        if(tabla.getSelectedRow() != -1) {
            int catidad = ((Integer) modeloPrueba.getValueAt(tabla.getSelectedRow(), 1));
            float precioNew = (((Producto) modeloPrueba.getValueAt(tabla.getSelectedRow(), 0)).getPrecio());
            float precioVergas = precioNew - ((precioNew)/catidad);
            total -= precioNew/catidad;//Estoy tomando el dinero que se va a quitar del total
            Producto producto = ((Producto) modeloPrueba.getValueAt(tabla.getSelectedRow(), 0));
            producto = new Producto(producto.getId(), producto.getNombre(), producto.getExistencia(), producto.getStock(), precioVergas, producto.getUM());
            if ((catidad - 1) == 0) {
                modeloPrueba.removeRow(tabla.getSelectedRow());
            } else {
                modeloPrueba.setValueAt(catidad - 1, tabla.getSelectedRow(), 1);
                modeloPrueba.setValueAt(producto, tabla.getSelectedRow(), 0);
            }
            
        } else {
            JOptionPane.showMessageDialog(this, "Favor de seleccionar un producto de la tabla de ventas", "Sin seleccion", JOptionPane.INFORMATION_MESSAGE);
        }
        actualizarTotal();
        actualizarCambio();
    }//GEN-LAST:event_btnQuitarActionPerformed

    private void btnNewCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewCActionPerformed
        String pagoEnString = txtPago.getText();
        float pagoEnFloat = 0;
        if (pagoEnString.equals("")) {
            pagoEnFloat = 0;
        } else {
            pagoEnFloat = Float.valueOf(txtPago.getText());
        }
        if ((!(pagoEnString.equals(""))) && pagoEnFloat >= 0 && (Double.valueOf(pagoS) - total) >= 0) {
            procesoDeVenta(0);
        } else {
            procesoDeVenta(1);
        }
    }//GEN-LAST:event_btnNewCActionPerformed

    private void txtPagoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPagoKeyTyped
        char c = evt.getKeyChar();
        if (c >= 48 && c <= 57 || c == 8 || c==46) {
            if( c == 8) {
                pagoS = pagoS.substring(0, pagoS.length()-1);
            } else {
                pagoS = pagoS.concat(String.valueOf(c));
            }
        } else {
            JOptionPane.showMessageDialog(this, "El caracter " + c + " no es valido", "Caracter Invalido", JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }
        actualizarCambio();
    }//GEN-LAST:event_txtPagoKeyTyped

    private void btnRadioIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRadioIDMouseClicked
        limpiarTxtYTabla();
    }//GEN-LAST:event_btnRadioIDMouseClicked

    private void btnRadioNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRadioNombreMouseClicked
        limpiarTxtYTabla();
    }//GEN-LAST:event_btnRadioNombreMouseClicked

    private void btnRadioPrecioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRadioPrecioMouseClicked
        limpiarTxtYTabla();
    }//GEN-LAST:event_btnRadioPrecioMouseClicked

    private void btnRadioCantidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRadioCantidadMouseClicked
        limpiarTxtYTabla();
    }//GEN-LAST:event_btnRadioCantidadMouseClicked

    private void ConsVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsVentaActionPerformed
        ConsultarVenta consultarVenta = new ConsultarVenta(100);
        consultarVenta.setVisible(true);
    }//GEN-LAST:event_ConsVentaActionPerformed

    private void BarraBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BarraBuscarKeyReleased
        if (btnRadioID.isSelected()) {
            consultarSQL(BarraBuscar.getText(), 1);
        } else if (btnRadioNombre.isSelected()) {
            consultarSQL(BarraBuscar.getText(), 2);
        } else if (btnRadioPrecio.isSelected()) {
            consultarSQL(BarraBuscar.getText(), 3);
        } else if (btnRadioCantidad.isSelected()) {
            consultarSQL(BarraBuscar.getText(), 4);
        }
    }//GEN-LAST:event_BarraBuscarKeyReleased

    private void ClienteTXTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ClienteTXTKeyReleased
        llenarLista(ClienteTXT.getText());
    }//GEN-LAST:event_ClienteTXTKeyReleased

    private void ListaClienteMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaClienteMouseMoved
        ClienteConPrecio.setText(ListaCliente.getSelectedValue());
    }//GEN-LAST:event_ListaClienteMouseMoved

    //-----------------Metodos-----------------------------
    
    //-------------------Metodo para poner el total dinamicamente----------------------
    public void actualizarTotal() {
        DecimalFormat df = new DecimalFormat("0.00");
        df.setRoundingMode(RoundingMode.UP);
        txtTotal.setText("$ " +  df.format(total));
    }
    //----------------------Cambio actualizado----------------------------
    public void actualizarCambio() {
        DecimalFormat df = new DecimalFormat("0.00");
        Double result = (Double.valueOf(pagoS) - total);
        df.setRoundingMode(RoundingMode.UP);
        txtCambio.setText("$ " + df.format(result));
    }

    public void limpiarTxtYTabla() {
        BarraBuscar.setText("");
        consultarSQL("", 0);
    }
    /**
     * Hace la consulta dependiendo el filtro que se aplique
     * @param consulta
     * @param filtro 
     */
    public void consultarSQL(String consulta, int filtro) {
        ListaCola<Producto> queue = new ListaCola<Producto>();
        
        Producto seihin;
        try {
            queue = mUIP.consulta(filtro, consulta);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "ERROR: " + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        vaciarTabla();
        while (true) {
            if (!queue.hasNext()) {
                break;
            }
            seihin = queue.pop();
            String[] datos = {String.valueOf(seihin.getId()), seihin.getNombre(),String.valueOf(seihin.getPrecio()),
            String.valueOf(seihin.getExistencia()), String.valueOf(seihin.getStock()), seihin.getUM()};
            modeloTablaAlmacen.addRow(datos);
        }
    }
    
    /**
     * Metodo para buscar un cliente o varios clientes con los caracteres introducidos
     * @param nombreC Nombre del cliente a buscar o parte del nombre
     * @return Cola de los clientes con el que el nombre coincide
     */
    public ListaCola<Clientes> consultarCliente(String nombreC){
        ListaCola<Clientes> queue = new ListaCola<Clientes>();
        try {
            if (nombreC.equals("")) {
                queue = mUIC.consulta(1, nombreC);
            } else {
                queue = mUIC.consulta(2, nombreC);
            }
        } catch (SQLException e) {
        }
        return queue;
    }
    /**
     * Metodo para obtener el Cliente seleccionado a vender
     * @param nombreC Nombre del cliente seleccionado en la lista de cliente
     * @return Cliente
     */
    public Clientes obtenerCliente(String nombreC){
        ListaCola<Clientes> queue = consultarCliente(nombreC);
        Clientes okyakusama;
        return okyakusama = queue.pop();
    }
    /**
     * Metodo para llenar la lista clientes
     * @param nombreC Nombre del cliente a buscar o parte del nombre
     */
    public void llenarLista(String nombreC){
        ListaCola<Clientes> queue = consultarCliente(nombreC);
        Clientes okyakusama;
        listaBase();
        while (true) {            
            if (!queue.hasNext()) {
                break;
            }
            okyakusama = queue.pop();
            modeloLista.addElement(okyakusama.getNombre());
        }
    }
    /**
     * Metodo para vaciar la tabla 
     * Si esto falla o marca error cambiar el for por 
     * for(int i = 0; i < modeloTabla2.getRowCount(); i++)
     */
    public void vaciarTabla() {
        for (int i =  modeloTablaAlmacen.getRowCount() - 1; i >= 0; i--) {
            modeloTablaAlmacen.removeRow(i);
        }
    }
    /**
     * Metodo para basiar la lista para agregar elemnentos nuevos sin que se dupliquen
     */
    public void listaBase(){
        modeloLista.removeAllElements();
    }
    /**
     * Metodo para finalizar una venta
     */
    public void finalizarVenta(){
        for (int i = modeloPrueba.getRowCount() - 1; i >= 0; i--) {
                modeloPrueba.removeRow(i);
            }
            txtPago.setText("");
            total = 0;
            pagoS = "0";
            actualizarTotal();
            actualizarCambio();
            consultarSQL("", 0);
    }
    /**
     * Metodo que realiza todos los procesos necesarios para realizar una venta
     * @param deuda 0 = No le falta dinero pero le puede sobrar <br>
     *              1 = Le falta dinero pero puede deberlo
     */
    public void procesoDeVenta(int deuda){
        int paso = 2;
        Clientes okyakusama = obtenerCliente(ListaCliente.getSelectedValue());
        try {
            paso = mIUVD.agregar(okyakusama.getId(), total);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "ERROR: " + ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        if (paso == 1) {
            //TODO: Declarar un arreglo que agregue cada producto ingresado
            int rowCount = modeloPrueba.getRowCount();
            VentaProductoUnitario[] productos = new VentaProductoUnitario[rowCount];
            VentaProductoUnitario productoUnitario;
            for (int i = 0; i < rowCount; i++) {
                try {
                    Producto producto = ((Producto) modeloPrueba.getValueAt(i, 0));
                    int id = producto.getId();
                    int cantidad = ((Integer) modeloPrueba.getValueAt(i, 1));
                    float subTotal = (producto.getPrecio());
                    float subTotalIV = subTotal/cantidad;
                    productoUnitario = new VentaProductoUnitario(producto, cantidad, subTotalIV, total);
                    productos[i] = productoUnitario;
                    mUIV.agregar(id, cantidad, subTotalIV);
                    //Aqui mismo puedo agregar la actualizacion de la cantidad que el producto tendra despues de que se vendio
                    mUIP.acutalizarExistencia(id, producto.getExistencia() - cantidad); //Pero claro, no se que tan facil sea esto ya que no lo puedo probar porque tengo error en otras clases que no son las mias xd
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "ERROR: " + ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            }
            if(deuda == 0){
                int seleccion = JOptionPane.showConfirmDialog(this, "El cambio es " + txtCambio.getText() + "\n Quiere guardar el cambio como saldo acredor del cliente?", "Venta realizada con exito",JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE);
                if (seleccion == 0) {
                    try {
                        String sinFeria = txtCambio.getText();
                        sinFeria = sinFeria.substring(2, sinFeria.length());
                        double cambio = Double.parseDouble(sinFeria);
                        int cambioTrucado = (int) cambio;
                        mUIC.modificar(okyakusama.getId(), okyakusama.getNombre(), Integer.parseInt(okyakusama.getSaldo()) + cambioTrucado);
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(this, "ERROR: " + ex.getMessage(), "ERROR en el cambio", JOptionPane.ERROR_MESSAGE);
                    }
                }
                finalizarVenta();
            } else {
                int seleccion = JOptionPane.showConfirmDialog(this, "Falta dinero " + txtCambio.getText() + "\n Quiere guardar el dinero faltante como saldo deudor del cliente?", "Venta con falta de dinero",JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE);
                if (seleccion == 0) {
                    try {
                        String sinFeria = txtCambio.getText();
                        sinFeria = sinFeria.substring(2, sinFeria.length());
                        double cambio = Double.parseDouble(sinFeria);
                        int cambioTrucado = (int) Math.ceil(-1*cambio);
                        mUIC.modificar(okyakusama.getId(), okyakusama.getNombre(), Integer.parseInt(okyakusama.getSaldo()) + (-1*cambioTrucado));
                        finalizarVenta();
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(this, "ERROR: " + ex.getMessage(), "ERROR en el cambio", JOptionPane.ERROR_MESSAGE);
                    }
                finalizarVenta();
                }
            }
            //TODO: Llamar al metodo para imprimir tickets
            // Pasarle al metodo el arreglo antes declarado
            printer.printTicket(productos);
        }
    }
    
    //--------------Fin Metodos----------------------------

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BarraBuscar;
    private javax.swing.JLabel ClienteBuscarLabel;
    private javax.swing.JLabel ClienteConPrecio;
    private javax.swing.JTextField ClienteTXT;
    private javax.swing.JButton ConsVenta;
    private javax.swing.ButtonGroup GrupoBtnRadio;
    private javax.swing.JList<String> ListaCliente;
    private javax.swing.JButton btnAgregarlist2;
    private javax.swing.JButton btnNewC;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JRadioButton btnRadioCantidad;
    private javax.swing.JRadioButton btnRadioID;
    private javax.swing.JRadioButton btnRadioNombre;
    private javax.swing.JRadioButton btnRadioPrecio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTable tabla;
    private javax.swing.JTable tablaAlmacen;
    private javax.swing.JTextField txtCambio;
    private javax.swing.JTextField txtPago;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
