/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import res.Producto;
/**
 *
 * @author vival
 */
public class GestionarVentas extends javax.swing.JPanel {

    DefaultListModel<Producto> modeloLista;
    DefaultTableModel modeloTablaAlmacen;
    static String[] cabeceraTablaAlmacen = {"ID", "Nombre", "Precio", "Existencia", "Stock", "Unidad de Medida"};
    static double total = 0;
    static String pagoS = "0";
    /**
     * Creates new form GestionarVentas
     */
    public GestionarVentas() {
        initComponents();
        GrupoBtnRadio.add(btnRadioID);
        GrupoBtnRadio.add(btnRadioCantidad);
        GrupoBtnRadio.add(btnRadioNombre);
        GrupoBtnRadio.add(btnRadioPrecio);
        
        btnRadioID.setSelected(true);
        
        modeloTablaAlmacen = new DefaultTableModel(null,cabeceraTablaAlmacen);
        tablaAlmacen.setModel(modeloTablaAlmacen);
        tablaAlmacen.getTableHeader().setReorderingAllowed(false);
        modeloLista = new DefaultListModel<Producto>();
        ListaVenta.setModel(modeloLista);
        llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoBtnRadio = new javax.swing.ButtonGroup();
        txtPago = new javax.swing.JTextField();
        searchBar = new javax.swing.JTextField();
        scrollSeleccionado = new javax.swing.JScrollPane();
        ListaVenta = new javax.swing.JList<>();
        btnClean = new javax.swing.JButton();
        btnAgregarlist2 = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();
        labelTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnNewC = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAlmacen = new javax.swing.JTable();
        ConsCompra = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnRadioID = new javax.swing.JRadioButton();
        btnRadioNombre = new javax.swing.JRadioButton();
        btnRadioPrecio = new javax.swing.JRadioButton();
        btnRadioCantidad = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        txtCambio = new javax.swing.JTextField();

        txtPago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPagoKeyTyped(evt);
            }
        });

        searchBar.setText("Buscar");
        searchBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchBarKeyTyped(evt);
            }
        });

        ListaVenta.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        scrollSeleccionado.setViewportView(ListaVenta);

        btnClean.setText("X");
        btnClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanActionPerformed(evt);
            }
        });

        btnAgregarlist2.setText("Agregar");
        btnAgregarlist2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarlist2ActionPerformed(evt);
            }
        });

        btnQuitar.setText("Quitar");
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });

        labelTotal.setText("Total");

        txtTotal.setEditable(false);
        txtTotal.setText("$");

        btnNewC.setText("Finalizar compra");
        btnNewC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewCActionPerformed(evt);
            }
        });

        jLabel1.setText("Pago");

        tablaAlmacen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaAlmacen);

        ConsCompra.setText("Consultar Ventas");
        ConsCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsCompraActionPerformed(evt);
            }
        });

        jLabel3.setText("Filtrar por:");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Gestionar Ventas");

        btnRadioID.setText("ID");

        btnRadioNombre.setText("Nombre");

        btnRadioPrecio.setText("Precio");

        btnRadioCantidad.setText("Cantidad");

        jLabel2.setText("Cambio");

        txtCambio.setText("$");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCambio))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addComponent(txtPago))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTotal)
                        .addGap(26, 26, 26)
                        .addComponent(txtTotal))
                    .addComponent(scrollSeleccionado, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                    .addComponent(btnNewC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnClean, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregarlist2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRadioID, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRadioNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRadioPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRadioCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(180, 180, 180)
                        .addComponent(ConsCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scrollSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(labelTotal))
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1))
                    .addComponent(txtPago, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2))
                    .addComponent(txtCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(btnNewC))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClean))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnQuitar)
                        .addGap(17, 17, 17)
                        .addComponent(btnAgregarlist2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(6, 6, 6)
                        .addComponent(btnRadioID)
                        .addGap(7, 7, 7)
                        .addComponent(btnRadioNombre))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRadioPrecio)
                                .addGap(7, 7, 7)
                                .addComponent(btnRadioCantidad))
                            .addComponent(ConsCompra))))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchBarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchBarKeyTyped

    }//GEN-LAST:event_searchBarKeyTyped

    private void btnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanActionPerformed

    }//GEN-LAST:event_btnCleanActionPerformed

    private void btnAgregarlist2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarlist2ActionPerformed
        if (tablaAlmacen.getSelectedRow() != -1 ) {
            String[] aux = new String[modeloTablaAlmacen.getColumnCount()];
           for (int i = 0; i < aux.length; i++) {
               aux[i] = modeloTablaAlmacen.getValueAt(tablaAlmacen.getSelectedRow(), i).toString();
           }
           
           Producto producto = new Producto(Integer.parseInt(aux[0]), aux[1], Integer.parseInt(aux[3]), Integer.parseInt(aux[4]), Float.valueOf(aux[2]), aux[5]);
           total += producto.getPrecio();
           modeloLista.addElement(producto);
           
        } else {
            JOptionPane.showMessageDialog(this, "Favor de seleccionar un producto de la tabla", "Sin seleccion", JOptionPane.INFORMATION_MESSAGE);
        }
        actualizarTotal();
        actualizarCambio();
    }//GEN-LAST:event_btnAgregarlist2ActionPerformed

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
        if(ListaVenta.getSelectedValue() != null && ListaVenta.getSelectedValue() instanceof Producto) {
            total -= modeloLista.get(ListaVenta.getSelectedIndex()).getPrecio();//Estoy tomando el dinero que se va a quitar del total
            modeloLista.removeElementAt(ListaVenta.getSelectedIndex());
        } else {
            JOptionPane.showMessageDialog(this, "Favor de seleccionar un producto de la lista", "Sin seleccion", JOptionPane.INFORMATION_MESSAGE);
        }
        actualizarTotal();
    }//GEN-LAST:event_btnQuitarActionPerformed

    private void btnNewCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewCActionPerformed
        if (!txtPago.getText().equals("")) {
            JOptionPane.showConfirmDialog(this, "Jajajajajajaj, no se como hacer la tabla que contendra lo de ventas, se pone ventas detalladas o ventas en general ya ni se",
                    String.valueOf(Double.valueOf(txtPago.getText()) - total),JOptionPane.ERROR_MESSAGE);
            modeloLista.removeAllElements();
            txtPago.setText("");
            total = 0;
            pagoS = "0";
            actualizarTotal();
            actualizarCambio();
        }
    }//GEN-LAST:event_btnNewCActionPerformed

    private void ConsCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsCompraActionPerformed
        ConsultarVenta consultarVenta = new ConsultarVenta(100);
        consultarVenta.setVisible(true);
    }//GEN-LAST:event_ConsCompraActionPerformed

    private void txtPagoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPagoKeyTyped
        char c = evt.getKeyChar();
        if (c >= 48 && c <= 57 || c == 8) {
            if( c == 8) {
                pagoS = pagoS.substring(0, pagoS.length()-1);
            } else {
                pagoS = pagoS.concat(String.valueOf(c));
            }
        } else {
            JOptionPane.showMessageDialog(this, "El caracter " + c + " no es valido", "Caracter Invalido", JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }
        actualizarCambio();
    }//GEN-LAST:event_txtPagoKeyTyped

    //-----------------Metodos-----------------------------
    
    //--------------Metodo llenar tabla-------------------
    public void llenarTabla() {
        /**
         * No estoy seguro de como se va a llenar la tabla tando de ventas como de almacen y cualquier otra tabla
         * Asi que por el no saber, lo que voy a hacer es poner productos modelo para simular que ya hay productos en la tabla
         */
        String[] datos1 = {"1","Pepsi", "20", "10", "10", "Empaquetado"};
        String[] datos2 = {"2","Sabritas", "13", "5", "10", "Empaquetado"};
        modeloTablaAlmacen.addRow(datos1);
        modeloTablaAlmacen.addRow(datos2);
        
    }
    
    //-------------------Metodo para poner el total dinamicamente----------------------
    public void actualizarTotal() {
        txtTotal.setText("$ " + total);
    }
    //----------------------Cambio actualizado----------------------------
    public void actualizarCambio() {
        txtCambio.setText("$ " + (Double.valueOf(pagoS) - total));
    }

    
    //--------------Fin Metodos----------------------------

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConsCompra;
    private javax.swing.ButtonGroup GrupoBtnRadio;
    private javax.swing.JList<Producto> ListaVenta;
    private javax.swing.JButton btnAgregarlist2;
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnNewC;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JRadioButton btnRadioCantidad;
    private javax.swing.JRadioButton btnRadioID;
    private javax.swing.JRadioButton btnRadioNombre;
    private javax.swing.JRadioButton btnRadioPrecio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JScrollPane scrollSeleccionado;
    private javax.swing.JTextField searchBar;
    private javax.swing.JTable tablaAlmacen;
    private javax.swing.JTextField txtCambio;
    private javax.swing.JTextField txtPago;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
